INSERT INTO `GENDER` (`ID`,`NAME`,`DATE_CREATED`) VALUES(1,'MALE',CURRENT_TIMESTAMP),(2,'FEMALE',CURRENT_TIMESTAMP);

INSERT INTO `DEPARTMENT` (`ID`,`NAME`,`DATE_CREATED`) VALUES(1,'Finance',CURRENT_TIMESTAMP),(2,'Operation',CURRENT_TIMESTAMP),(3,'Assets',CURRENT_TIMESTAMP),(4,'HR',CURRENT_TIMESTAMP);

INSERT INTO `EMP` (`ID`,`FNAME`,`LNAME`,`DOB`,`DEPARTMENT_ID`,`GENDER_ID`,`DATE_CREATED`)
 VALUES(1,'Mr Bean','Bean','1977-02-02',1,1,CURRENT_TIMESTAMP);